User.create!([
  {session_token: "Ln5FRzNZ2FUz8IQJjbEn5w", password_digest: "$2a$10$qftgE00xqTU8zlsPvrA72eyNUc3sZLbF3b0E1QvqrnuJSDkQ13sOC", email: "foo@gmail.com", name: "Jacob Kopczynski"},
  {session_token: "7bdMbEmHh4xky3GzFsLWnw", password_digest: "$2a$10$fw6hAwZkqKmNukfp3SrCZ.x/lujnP.wTKtOCRazxM15CGi8Fj4BJG", email: "0@sidetable.us", name: "Man of Mystery"},
  {session_token: "FY1hWFP26noER-dXfUxeaw", password_digest: "$2a$10$ls6Mve2A8O7HVR7dniudYei7iUUV3dWT3HdIgPCMs2g8vb0HbzH5y", email: "1@sidetable.us", name: "Man of Mystery"},
  {session_token: "nX8rAxknQ1Vz217aCBgrLA", password_digest: "$2a$10$t6pv3xrDjuIezxNDRDN9yeYATcy9Mlfll8xvfxjaiPGGFKmXsKgFa", email: "8@sidetable.us", name: "Man of Mystery"},
  {session_token: "dKgvzHUoODYEEUvhhmze5Q", password_digest: "$2a$10$D67A51k0OxCU2KTlU5MDWuNJTuwiKewkPNq0NpugSpWFzsHLZR.IW", email: "27@sidetable.us", name: "Man of Mystery"},
  {session_token: "DAa4StHtI6AwHua57o105g", password_digest: "$2a$10$vvuTqUcePNeI6F3UP8ivY.p1uCj2dcBJAbGJI0/TydalsiCelLWbK", email: "64@sidetable.us", name: "Man of Mystery"},
  {session_token: "Kpkc5q4RVEjbNWBriIOquQ", password_digest: "$2a$10$vGfHLAGp68bTuJrAui01h.xhgr4hTq49pMtpPD3WgFKdQK10CVchy", email: "125@sidetable.us", name: "Man of Mystery"},
  {session_token: "8ofG0eOAwzQrj9mhdNCVBA", password_digest: "$2a$10$kKtzB0QSrCf4o1ghhWcjveGCMe4maeX6ITXNpcD7Tmr1wiLiBhPKW", email: "216@sidetable.us", name: "Man of Mystery"},
  {session_token: "p5nANY6ObHrVWihp_g1V7A", password_digest: "$2a$10$vZpYS.tPJ/wNpW397uGEaOQa9PeqMSi57eDFNVM0KyNxuq2FI5ucu", email: "343@sidetable.us", name: "Man of Mystery"},
  {session_token: "8IZ8gPNRPiZliQNrbnEqaQ", password_digest: "$2a$10$72xFuXS0lu3i16TKcEUWv.Sc.zckSyZS22p5Ejjeu8vTAxMKZ1Tqe", email: "512@sidetable.us", name: "Man of Mystery"},
  {session_token: "yjJQNaYUxHjS215H7dRB9Q", password_digest: "$2a$10$pQ5a.jJfolkKLbMdpaerOuDqCJBqTWYLV7yIWqRHJBVWElCFlgqFS", email: "729@sidetable.us", name: "Man of Mystery"},
  {session_token: "aYQUwX8mcYXnvXLRw8wPHw", password_digest: "$2a$10$E4isE41LeSk8IcIs5MBgSuO7y612NjDJhkpPLvMVWfuAhkL461vza", email: "1000@sidetable.us", name: "Man of Mystery"},
  {session_token: "ePVuwtQV3toETJ_7C3wiSw", password_digest: "$2a$10$wEbrzfunpTuu856KONdo/ONOwYYlb30es2sdh6XDpLuIjugtOXxzq", email: "1331@sidetable.us", name: "Man of Mystery"},
  {session_token: "T9HorkjZH29uuhFFcrGwSw", password_digest: "$2a$10$dlDfHsd1FH.dCHdc2i78s.0oSCVXnm03hrJXbkMHIXCoOMubcEqI2", email: "1728@sidetable.us", name: "Man of Mystery"},
  {session_token: "rSIe3iu3In2EgH-lBYL7Bg", password_digest: "$2a$10$vPvrzbGrS00oKUKMRT6CDe6dYGTyQ8StxPmLiA8wteeohV5Wgnxp.", email: "2197@sidetable.us", name: "Man of Mystery"},
  {session_token: "Z65cIEkt2b-J7nVmWhSXSQ", password_digest: "$2a$10$hkTGXSrcsa3CoKTKXdCXiOHBCFvxT8ziihcRrWTvMeO/KDUX7GNv2", email: "2744@sidetable.us", name: "Man of Mystery"},
  {session_token: "G2c2QmaJobcAvzyR7oXJjQ", password_digest: "$2a$10$IjPEKYVYemkZgHZPdNzcAuNLV2tI.GzqAGzAEtf/FeWDeJS557zDq", email: "3375@sidetable.us", name: "Man of Mystery"},
  {session_token: "g1TSpvmlDx0ybvFwdmSPhw", password_digest: "$2a$10$tAU9sKnKleDZ/fjgbOwNh.tAe.Yd6ul3knifnkuwjlK1.9ZS96v.y", email: "4096@sidetable.us", name: "Man of Mystery"},
  {session_token: "Lz1QHhO1-MM5XUOdF-ueDA", password_digest: "$2a$10$ip2eAlanHTniXTDP/ZnYCOh8nh7RRJgUGI2cJq6/tE6gpBWRMH8ii", email: "random@random.org", name: "Anonymous Coward"},
  {session_token: "oa1T72rQIX6soQc1U4VpYQ", password_digest: "$2a$10$1/NdWw78/EHM5b3J2Kdxi.iyrmrBQ1njzLH0w28/dC39kMffqxCtW", email: "bar@gmail.com", name: "John Doe"}
])
Game.create!([
  {title: "Settlers of Catan", image_url: "http://www.mayfairgames.com/mfg-shop3/MFG3000-3099/large/MFG3061-cl.jpg", designer: "Klaus Teuber", description: "In Catan (formerly The Settlers of Catan), players try to be the dominant force on the island of Catan by building settlements, cities, and roads. On each turn dice are rolled to determine what resources the island produces. Players collect these resources (cards)—wood, grain, brick, sheep, or stone—to build up their civilizations to get to 10 victory points and win the game.\n    \n    Setup includes randomly placing large hexagonal tiles (each showing a resource or the desert) in a honeycomb shape and surrounding them with water tiles, some of which contain ports of exchange. Number disks, which will correspond to die rolls (two 6-sided dice are used), are placed on each resource tile. Each player is given two settlements (think: houses) and roads (sticks) which are, in turn, placed on intersections and borders of the resource tiles. Players collect a hand of resource cards based on which hex tiles their last-placed house is adjacent to. A robber pawn is placed on the desert tile.\n    \n    A turn consists of possibly playing a development card, rolling the dice, everyone (perhaps) collecting resource cards based on the roll and position of houses (or upgraded cities—think: hotels) unless a 7 is rolled, turning in resource cards (if possible and desired) for improvements, trading cards at a port, and trading resource cards with other players. If a 7 is rolled, the active player moves the robber to a new hex tile and steals resource cards from other players who have built structures adjacent to that tile.\n    \n    Points are accumulated by building settlements and cities, having the longest road and the largest army (from some of the development cards), and gathering certain development cards that simply award victory points. When a player has gathered 10 points (some of which may be held in secret), he announces his total and claims the win.\n    \n    Catan has won multiple awards and is one of the most popular games in recent history due to its amazing ability to appeal to experienced gamers as well as those new to the hobby."},
  {title: "Smallworld", image_url: "http://www.blogcdn.com/www.tuaw.com/media/2010/05/small-world-01-630-1273190451.jpg", designer: "Philippe Keyaerts", description: "Small World is inhabited by a zany cast of characters such as dwarves, wizards, amazons, giants, orcs and even humans; who use their troops to occupy territory and conquer adjacent lands in order to push the other races off the face of the earth."},
  {title: "Carcassone", image_url: "https://www.filofilo.com/imagedb/gallery/1092_1711.jpg", designer: "Klaus-Jürgen Wrede", description: "In Carcassonne, players build the area surrounding this impressive city, one tile at a time. They then place a follower on fields, cities, roads or monasteries in order to score as many points as possible. These followers will become knights, monks, farmers and thieves, depending on where they are placed. No matter their followers' function, the player who will most cleverly use their followers will win the game...\n   \n   CARCASSONNE – A simple tactical game that offers a unique experience. A majestic way to discover a new world!"},
  {title: "Dominion", image_url: "http://riograndegames.com/uploads/Game/Preview-1_278.jpeg", designer: "Donald X. Vaccarino", description: "You are a monarch, like your parents before you, a ruler of a small pleasant kingdom of rivers and evergreens. Unlike your parents, however, you have hopes and dreams! You want a bigger and more pleasant kingdom, with more rivers and a wider variety of trees. You want a Dominion!  In all directions lie fiefs, freeholds, and feodums. All are small bits of land, controlled by petty lords and verging on anarchy. You will bring civilization to these people, uniting them under your banner. \n    \n    But wait! It must be something in the air; several other monarchs have had the exact same idea. You must race to get as much of the unclaimed land as possible, fending them off along the way. To do this you will hire minions, construct buildings, spruce up your castle, and fill the coffers of your treasury. Your parents wouldn’t be proud, but your grandparents would be delighted."},
  {title: "Pandemic", image_url: "https://clevergamereference.files.wordpress.com/2015/01/pandemic.jpg", designer: "Matt Leacock", description: "Four diseases have broken out in the world and it is up to a team of specialists in various fields to find cures for these diseases before mankind is wiped out.\n    Players must work together, playing to their characters’ strengths and planning their strategy of eradication before the diseases overwhelm the world with ever-increasing outbreaks. But the diseases are outbreaking fast and time is running out: the team must try to stem the tide of infection in diseased areas while also towards cures.\n    A truly cooperative game where you all win or you all lose."},
  {title: "Zaibatsu", image_url: "http://i.imgur.com/5vN9hvy.jpg", designer: "Jacob Kopczynski", description: "A fast-paced auction game for 2-4 players. Bid on collections of companies to gain control of your supply chain and dominate the economy. The strongest collection after four rounds will control the economy as the most dominant Zaibatsu!"},
  {title: "Ticket To Ride", image_url: "http://ecx.images-amazon.com/images/I/61dDQUfhuvL._SX300_.jpg", designer: "Alan R. Moon", description: "th elegantly simple gameplay, Ticket to Ride can be learned in under 15 minutes, while providing players with intense strategic and tactical decisions every turn. Players collect cards of various types of train cars they then use to claim railway routes in North America. The longer the routes, the more points they earn. Additional points come to those who fulfill Destination Tickets – goal cards that connect distant cities; and to the player who builds the longest continuous route.\n    \n    'The rules are simple enough to write on a train ticket – each turn you either draw more cards, claim a route, or get additional Destination Tickets,' says Ticket to Ride designer, Alan R. Moon. 'The tension comes from being forced to balance greed – adding more cards to your hand, and fear – losing a critical route to a competitor.'"},
  {title: "7 Wonders", image_url: "http://upload.wikimedia.org/wikipedia/en/7/7e/7_wonders_board_game_cover.jpg", designer: "Antoine Bauza", description: "In 7 Wonders, you lead an ancient civilization as it rises from its barbaric roots to become a world power. Lead your troops to a military victory or create a nation of artisans and philosophers. Establish a powerful merchant state or master the mysteries of science and technology. Build an architectural wonder that will fascinate for eons to come, and rule the most powerful civilization on Earth!"},
  {title: "Race for the Galaxy", image_url: "http://www.herebebooks.com/onlinestore/img/p/20-285-thickbox.jpg", designer: "Thomas Lehmann", description: "In Race for the Galaxy, players build galactic civilizations by game cards that represent worlds or technical and social developments.Each round consists of one or more of five possible phases. In each round, each player secretly and simultaneously chooses one of seven different action cards and then reveals it. Only the selected phases occur. For these phases, every player performs the phase’s action, while the selecting player(s) also get a bonus for that phase.For example, if at least one player chooses the Develop action, then the Develop phase will occur; otherwise it is skipped. In it, each player may simultaneously select a development from his hand of cards to build. After revealing the cards, each player adds his development to his tableau of cards on the table and then discards cards from his hand equal to its cost. Each player who chose Develop discards one card fewer as his bonus.Explore allows a player to draw cards and select which of them to add to his hand. Settle allows a player to place a world in his tableau. Some worlds produce goods, represented by face down cards, when Produce is selected. These goods can be discarded for victory points or sold to add cards to the player’s hand by selecting Consume. With cards, players can settle new worlds and build more developments, gaining both victory points and card powers that provide advantages in certain phases.The player who best manages his cards, phase and bonus selections, and card powers to build the greatest space empire, wins.The winner is the player with the most victory points."},
  {title: "Bohnanza", image_url: "http://riograndegames.com/uploads/Game/Preview-1_36.jpeg", designer: "Uwe Rosenberg", description: "This great card game is about planting, trading, and selling beans - 11 kinds of beans. Players try to collect large sets of beans to sell for gold. There is limited growing space and always new beans to plant. To avoid planting unwanted beans, players trade them to other players who want them for their bean fields."},
  {title: "King of Tokyo", image_url: "http://www.iellogames.com/images/KingOfTokyo_3Dbox.jpg", designer: "Richard Garfield", description: "IT'S RAMPAGE TIME!\n     \n    Play mutant monsters, gigantic robots and other monstrous creatures, rampaging the city and vying for position as the one and only King of Tokyo!\n    \n    Combine your dice to gather energy, heal your monster or just slap the other monsters down! Spend your energy to trigger permanent or one-shot special powers: a second head, body armor, nova death ray...\n      \n      Stop at nothing to become the King of Tokyo... but that’s when the real trouble begins for you!"},
  {title: "Stone Age", image_url: "http://upload.wikimedia.org/wikipedia/en/5/50/Stone_Age_game.jpg", designer: "Bernd Brunnhofer", description: "The Dawn of Mankind. Our ancestors were hard workers, resting only very little. Luckily for us, their ingenuity allowed them to make their work easier, day after day. In Stone Age, players are sent back to that arduous period of history. With tools, quite archaic at first, you will be able to collect wood, stone and gold. These resources will allow you to attain higher levels of knowledge and build sturdier roofs over your head. Though luck plays an im­portant part in the game, only those who master their fate will be able to grasp victory. Finally, one mustn’t forget to feed their tribe, as that would represent a major setback for them.\n   Relive history!\n    \n    Carve your victory in stone!"},
  {title: "Lost Cities", image_url: "http://riograndegames.com/uploads/Game/Preview-1_126.jpeg", designer: "Reiner Knizia", description: "For the daring and adventurous, there are many lost cities to explore. They are in the Himalayas, the ever-shifting sands of the desert, the Brazilian rain forest, ancient volcanoes and in Neptune’s Realm. With limited resources the players must choose which expeditions to begin. Those with high confidence may want to up the stakes: increasing the rewards for success, but risking more should the expedition fail. The player who finds the right balance will find victory!"},
  {title: "Munchkin", image_url: "http://www.worldofmunchkin.com/game/img/cover_lg.jpg", designer: "Steve Jackson", description: "Go down in the dungeon. Kill everything you meet. Backstab your friends and steal their stuff. Grab the treasure and run.\n    Admit it. You love it.\n    Munchkin is the mega-hit card game about dungeon adventure . . . with none of that stupid roleplaying stuff. You and your friends compete to kill monsters and grab magic items. And what magic items! Don the Horny Helmet and the Boots of Butt-Kicking. Wield the Staff of Napalm . . . or maybe the Chainsaw of Bloody Dismemberment. Start by slaughtering the Potted Plant and the Drooling Slime, and work your way up to the Plutonium Dragon . . .\n    Fast-playing and silly, Munchkin can reduce any roleplaying group to hysteria. And, while they're laughing, you can steal their stuff."},
  {title: "Battlestar Galactica", image_url: "https://cf.geekdo-images.com/images/pic354500.jpg", designer: "Corey Konieczka", description: "The Cylons were created to make life easier on the Twelve Colonies, before the day when the Cylons decided to kill their masters. After a long and bloody struggle, an armistice was declared and the Cylons left for another world to call their own. Forty years later, they returned, and brought humanity to the brink of extinction. The remaining humans, led by the crew of the Battlestar Galactica, fled in hope of finding a new home, one known by legend as Earth. Humanity’s only hope lies in finding Earth’s location while fighting off the unrelenting Cylons. But as resources run low, it is discovered that the enemy can now appear human and has infiltrated the fleet from the inside.\n     \n     Battlestar Galactica: The Board Game provides a unique gaming experience. Unlike most games where players win individually, Battlestar Galactica is a cooperative game, with the added complication that one or more of the players is a secret Cylon traitor – your entire side will win or lose, and you might not even be certain who is on your side until the game ends!"},
  {title: "Twilight Struggle", image_url: "http://i00.i.aliimg.com/wsphoto/v0/1543675900_1/-HomeMade-WarGame-font-b-Twilight-b-font-font-b-Struggle-b-font-The-Cold-War.jpg", designer: "Ananda Gupta & Jason Matthews", description: "In 1945, unlikely allies toppled Hitler's war machine, while humanity's most devastating weapons forced the Japanese Empire to its knees in a storm of fire. Where once there stood many great powers, there now stood only two – the United States and the Soviet Union. The world had scant months to collectively sigh in relief before a new conflict threatened. Unlike the titanic struggles of the preceding decades, this conflict would be waged not primarily by soldiers and tanks, but by spies and politicians, scientists and intellectuals, artists and traitors. Twilight Struggle is a two-player game simulating the 45 year dance of intrigue, prestige, and occasional flares of warfare between the USSR and the USA. The entire world is the stage on which these two titans fight. The game begins amidst the ruins of Europe as the two new superpowers scramble over the wreckage of WWII and ends in 1989, when only the United States remained standing.\n      \n      Twilight Struggle inherits its fundamental systems from the card-driven classics We the People and Hannibal. It is a quick-playing, low-complexity game in that same tradition. The game map is a world map of the period, whereon players move units and exert influence in attempts to gain allies and control for their superpower.\n      \n      Twilight Struggle's Event cards add detail and flavor to the game. They cover a vast array of historical happenings: the Arab-Israeli conflicts, Vietnam, the peace movement, the Cuban Missile Crisis, and other such incidents that brought the world to the brink of nuclear annihilation. Subsystems capture the prestige-laden Space Race as well as nuclear tensions, with the possibility of game-ending nuclear war. Can you, as the U.S. President or Soviet Premier, lead your nation to victory? Play Twilight Struggle and find out."},
  {title: "Caylus", image_url: "http://riograndegames.com/uploads/Game/Preview-1_65.jpeg", designer: "William Attia", description: "1289. To strengthen the borders of the Kingdom of France, King Philip the Fair decided to have a new castle built. For the time being, Caylus is but a humble village, but soon, workers and craftsmen will be flocking by the cartload, attracted by the great prospects. Around the building site, a city is slowly rising up. The players embody master builders. By building the King’s castle and developing the city around it, they earn prestige points and gain the King’s favor. When the castle is finished, the player who has earned the most prestige wins the game."},
  {title: "Lords of Waterdeep", image_url: "http://ecx.images-amazon.com/images/I/81tVInsxubL._SL1200_.jpg", designer: "Peter Lee and Rodney Thompson", description: "Waterdeep, the City of Splendors—the most resplendent jewel in the Forgotten Realms, and a den of political intrigue and shady back-alley dealings. In this game, the players are powerful lords vying for control of this great city. Its treasures and resources are ripe for the taking, and that which cannot be gained through trickery and negotiation must be taken by force!\n    \n    Lords of Waterdeep is a strategy board game for 2-5 players. You take on the role of one of the masked Lords of Waterdeep, secret rulers of the city. Through your agents, you recruit adventurers to go on quests on your behalf, earning rewards and increasing your influence over the city.\n    \n    Expand the city by purchasing new buildings that open up new actions on the board, and hinder—or help—the other lords by playing Intrigue cards to enact your carefully laid plans."},
  {title: "Shadows Over Camelot", image_url: "http://upload.wikimedia.org/wikipedia/en/5/56/Shadows_over_Camelot.jpg", designer: "Bruno Cathala and Serge Laget", description: "As the incarnation of the Knights of the Round Table, you join forces against the game itself in an attempt to protect Camelot.\n    \n    Your victory hinges on the successful completion of legendary Quests, such as the search for Excalibur, the Holy Grail, or Lancelot's Armor; the tournament against the Black Knight; and numerous wars against the Saxons and Picts.\n    \n    But beware... all is not as it seems among these noble Knights. One of your number might yet turn out to be a traitor-in-waiting, biding his time while sowing havoc and destruction from the Shadows!"},
  {title: "Risk", image_url: "http://gfbrobot.com/wp-content/uploads/2011/06/risk-funagain-com.jpg", designer: "Albert Lamorisse and Michael I. Levin", description: "The classic game of global war. Lead your troops. Take a risk. Rule the world! Rally your armies to march across continents. Carefully craft your strategy—you’ll face your opponents on the field of battle and they’ll give the fight everything they’ve got. Keep advancing until you’ve defeated all of your foes and taken over the world!"},
  {title: "Forbidden Island", image_url: "http://images.amazon.com/images/G/01/toys/detail-page/c26-B003D7F4YY-2-l.jpg", designer: "Matt Leacock", description: "Dare to discover Forbidden Island! Join a team of fearless adventurers on a do-or-die cooperative mission to capture four sacred treasures from the ruins of this perilous paradise. Your team will have to work together and make some pulse-pounding maneuvers, as the island will sink beneath every step! Race to collect the treasures and make a triumphant escape before you are swallowed into the watery abyss!"},
  {title: "Tigris & Euphrates", image_url: "http://www.mayfairgames.com/mfg-shop3/MFG4100-4199/large/MFG4116-cl.jpg", designer: "Reiner Knizia", description: "Culture, Conflict, Civilization!\n    \n    Step back to the dawn of recorded time. Take command of a young dynasty in fertile Mesopotamia. Here, between the Tigris and Euphrates rivers, lies the cradle of civilization. Here, as the Bible tells, rose man's first cities: Ur, Nineveh, and fair Babylon. Play a part in the epic saga of the rise of these great urban centers. Guide your dynasty to develop and control the most vibrant culture in the rich land between the two rivers.\n    \n    Create the best balance between markets, temples, settlements, and farms. Forge your own new civilization and dominate the rich valleys of the Tigris and Euphrates."},
  {title: "Alhambra", image_url: "http://www.boardgamequest.com/wp-content/uploads/2013/10/Alhambra.jpg", designer: "Dirk Henn", description: "Granada, 1278. At the foot of the Sierra Nevada mountains, one of the most exciting and interesting projects of the Spanish Middle Ages begins: the construction of Alhambra.\n    \n    Experience, over the course of the game, determines how the construction of this Spanish wonder takes place. The game is easy to learn: just a few rules and you're ready to play. \n    Each round, you must decide: Do you take a currency note, so that later on you can acquire a valuable piece of the Palace - a Pavilion or a Manor for example? "},
  {title: "Chess", image_url: "http://upload.wikimedia.org/wikipedia/commons/c/c3/Chess_board_opening_staunton.jpg", designer: "Traditional", description: "This ancient strategy game needs no introduction. Sometimes called the game of kings, it has been played in its current form for milennia."},
  {title: "RoboRally", image_url: "http://www.milan-spiele.de/images/ava007.jpg", designer: "Richard Garfield", description: "Robot Racing to the Extreme!\n    \n    As one of several supercomputers in a fully automated widget factory, you have it made.\n    \n    You are brilliant. \n    You are powerful. \n    You are sophisticated. \n    You are BORED.\n    \n    Time to enjoy a little fun at the factory's expense! With the other computers, program factory robots and pit them against each other in frantic, destructive races across the factory floors. Be the first to touch the flags, in order, and you win it all: the honor, the glory, the grudging respect of the other computers. But first you have to get your robot past obstacles like gaping pits, industrial lasers, moving conveyor belts and, of course, the other robots!"},
  {title: "San Juan", image_url: "http://cdn1.vox-cdn.com/assets/4193033/image01.jpg", designer: "Andreas Seyfarth", description: "Puerto Rico’s golden age returns. Through you! Players travel now to the capital city of this beautiful island. Who will build the most important buildings? Players build palaces, poor houses, silver smelters, gold mines, and many others - each with its own special features. The cleverest player will build well and win! As with the board game, players choose roles which can help all players, but the choosing player gets a special privilege with the role chosen. Players build buildings, produce and sell goods, and so on. The game is based on Puerto Rico, but different enough to give players new challenges and opportunities for fun and enjoyment."},
  {title: "Scrabble", image_url: "http://www.donaldsauter.com/1989-mb-box.jpg", designer: "Alfred Mosher Butts", description: "In this classic word game, players use their seven drawn letter-tiles to form words on the gameboard. Each word laid out earns points based on the commonality of the letters used, with certain board spaces giving bonuses. But a word can only be played if it uses at least one already-played tile or adds to an already-played word. This leads to slightly tactical play, as potential words are rejected because they would give an opponent too much access to the better bonus spaces."},
  {title: "El Grande", image_url: "http://940ee6dce6677fa01d25-0f55c9129972ac85d6b1f4e703468e6b.r99.cf2.rackcdn.com/products/pictures/112696.jpg", designer: "Wolfgang Kramer and Richard Ulrich", description: "The players are the Grandes in old Spain. Each wants to increase his influence at the court and in the regions. Each turn, the players choose from 5 actions, different on each turn. But first choice goes to the player who plays the highest priority card and you have only 13 for the game. Choose your actions and priorities wisely to become the most powerful Grande and win the game!"},
  {title: "Monopoly", image_url: "http://blog.mhcache.com/en/wp-content/uploads/2010/11/monopoly-box.jpg", designer: "Elizabeth Magie", description: "The infamous game of real estate markets. It needs no introduction, and if it does, count yourself lucky and stay far away."},
  {title: "Hive", image_url: "http://gen42.com/images/hivelogo_g42.jpg", designer: "John Yianni", description: "Hive is a board game with a difference. There is no board! The pieces are added to the playing area thus creating the board. As more and more pieces are added the game becomes a fight to see who can be the first to capture the opposing Queen Bee.\n    \n    The soldier ants battle to keep control of the outside of the hive, whilst the Beetles climb up to dominate the top. Spiders moving into holding positions as the Grass Hoppers jump in for the kill. Keeping one eye on the hive and the other on your opponents reserves, the tension builds as one wrong move will see your Queen Bee quickly engulfed; .... game over!"},
  {title: "Le Havre", image_url: "http://www.gamehead.com/sites/default/files/styles/gh_article_banner_teaser/public/images/article/thumb_files/1890/le-havre-ios-71a3ars.jpg?itok=x636eq4w", designer: "Uwe Rosenberg", description: "Manage a harbor, build ships and construct buildings in your bid to become \n    the merchant with the largest fortune and the most power in Le Havre. \n    Take control of resources, process them, sell them, and turn them into food \n    to feed your hungry workers. Construct or buy up buildings or ships to prove that you are the master of Le Havre!"},
  {title: "Eclipse", image_url: "http://meepletown.com/wp-content/uploads/2012/10/eclipse.jpg", designer: "Touko Tahkokallio", description: "The galaxy has been a peaceful place for many years. After the ruthless Terran–Hegemony War (30.027–33.364), much effort has been employed by all major spacefaring species to prevent the terrifying events from repeating themselves. The Galactic Council was formed to enforce precious peace, and it has taken many courageous efforts to prevent the escalation of malicious acts. Nevertheless, tension and discord are growing among the seven major species and in the Council itself. Old alliances are shattering, and hasty diplomatic treaties are made in secrecy. A confrontation of the superpowers seems inevitable – only the outcome of the galactic conflict remains to be seen. Which faction will emerge victorious and lead the galaxy under its rule?\n    \n    A game of Eclipse places you in control of a vast interstellar civilization, competing for success with its rivals. You will explore new star systems, research technologies, and build spaceships to wage war with. There are many potential paths to victory, so you need to plan your strategy according to the strengths and weaknesses of your species, while paying attention to the other civilizations' endeavors.\n    \n    The shadows of the great civilizations are about to eclipse the galaxy. Lead your people to victory!"},
  {title: "The Castles of Burgundy", image_url: "http://ecx.images-amazon.com/images/I/81ALqSnd1QL._SL1500_.jpg", designer: "Stefan Feld", description: "The Hundred Years’ war is over and the Renaissance is looming. Conditions are perfect for the princes of the Loire Valley to propel their estates to prosperity and prominence. Through strategic trading and building, clever planning, and careful thought, players add settlements and castles, practice trade along the river, exploit silver mines, farm livestock, and more in this classic Stefan Feld Eurogame."},
  {title: "Blokus", image_url: "https://images.funagain.com/cover/huge/14089.jpg", designer: "Bernard Tavitian", description: "Your whole family will enjoy Blokus, a board game with simple rules and lots of strategy! Place your colored pieces on the game board, but remember that they have to touch only the corner of at least one of the game pieces you have already played. As you play the block game, you will need to plan ahead to stretch into new territory and play you pieces before you run out of space! Once you learn to play Blokus, you'll want to keep trying new strategies to take over the board. Kids as young as 5 years old can play this fun building game for two to four players!"},
  {title: "Ra", image_url: "http://upload.wikimedia.org/wikipedia/en/5/53/Ra_game.jpg", designer: "Reiner Knizia", description: "Ra is set in ancient Egypt. The players strive for power by collecting tiles that represent various aspects of economic, spiritual, and technological growth. The players acquire the tiles by bidding for them in auctions. The currency for these auctions are tokens given to players by Ra, the sun God. Using these limited tokens, players must decide when to bid and how much to get the tiles they want."},
  {title: "Hanabi", image_url: "http://www.thegamernerd.com/wp-content/uploads/2014/07/hanabi-box-1.jpg", designer: "Antoine Bauza", description: "Players work cooperatively in this clever deduction card game with an electrifying twist! Each player is dealt a hand of 5 cards, but the catch is that you can see everyone's cards except your own. Working together, you must share (and remember!) vital information to play cards in the proper launch sequence. Light them all to create a dazzling display and avoid a fizzling fiasco!  2013 Spiel des Jahres winner, designed by Antoine Bauza."},
  {title: "BANG!", image_url: "https://techoraming.files.wordpress.com/2012/07/bang.jpg", designer: "Emiliano Sciarra", description: "The Outlaws hunt the Sheriff. The Sheriff hunts the Outlaws. The Renegade plots secretly, ready to take one side or the other. Bullets fly. Who among the gunmen is a Deputy, ready to sacrifice himself for the Sheriff? And who is a merciless Outlaw, willing to kill him? If you want to find out, just draw (your cards)!"},
  {title: "Alien Frontiers", image_url: "http://www.gamesalute.com/sites/default/files/styles/game_page_slider/public/af_boxfront_0.jpg?itok=-ZHBFRkS", designer: "Tory Niemann", description: "Do you have what it takes to be a deep space colonist? An alien frontier awaits the brave and daring! This new planet will be harsh, but if you have the skills to manage your resources, build a fleet, research alien life, and settle colonies, the world can be yours.\n   Alien Frontiers is a game of resource management and planetary development for two to four players. During the game you will utilize orbital facilities and alien technology to build colony domes in strategic locations to control the newly discovered world.\n   The game board shows the planet, its moon, the stations in orbit around the planet, and the solar system’s star. The dice you are given at the start of the game represent the space ships in your fleet. You will assign these ships to the orbital facilities in order to earn resources, expand your fleet, and colonize the planet.\n   As the game progresses, you will place your colony tokens on the planet to represent the amount of control you have over each territory. Those territories exert influence over specific orbital facilities and, if you control a territory, you are able to utilize that sway to your advantage.\n   The planet was once the home of an alien race and they left behind a wondrous artifact in orbit. Using your fleet to explore the artifact, you will discover amazing alien technologies that you can use to advance your cause.\n   Winning the game will require careful consideration as you assign your fleet, integrate the alien technology and territory influences into your expansion plans, and block your opponents from building colonies of their own. Do you have what it takes to conquer an alien frontier?"},
  {title: "Power Grid", image_url: "http://riograndegames.com/uploads/Game/Preview-1_5.jpeg", designer: "Friedemann Friese", description: "The object of Power Grid is to supply the most cities with power when someone's network gains a predetermined size. In this new edition, players mark pre-existing routes between cities for connection, and then bid against each other to purchase the power plants that they use to power their cities.\n      \n      However, as plants are purchased, newer, more efficient plants become available, so by merely purchasing, you're potentially allowing others access to superior equipment.\n      \n      Additionally, players must acquire the raw materials (coal, oil, garbage, and uranium) needed to power said plants (except for the 'renewable' windfarm/ solar plants, which require no fuel), making it a constant struggle to upgrade your plants for maximum efficiency while still retaining enough wealth to quickly expand your network to get the cheapest routes."},
  {title: "Puerto Rico", image_url: "http://upload.wikimedia.org/wikipedia/en/6/66/Puerto_Rico_game.jpg", designer: "Andreas Seyfarth", description: "Prospector, captain, mayor, trader, settler, craftsman, or builder?\n    Which roles will you play in the new world? Will you own the most prosperous plantations? Will you build the most valuable buildings? \n    You have but one goal: achieve the greatest prosperity and highest respect! "},
  {title: "Agricola", image_url: "http://upload.wikimedia.org/wikipedia/en/f/f6/Agricola_game.jpg", designer: "Uwe Rosenberg", description: "Agricola is a turn-based game. There are 14 game turns plus 6 harvest phases (after turn 4, 7, 9, 11, 13, and 14). Each player starts with two playing tokens (farmer and wife) and thus can take two actions per turn. There are multiple options, and while the game progresses, you’ll have more and more: fi rst thing in a turn, a new action card is fl ipped over.\n    Problem: Each action can be taken just once per turn, so it’s important to do some things with high preference. Each player also starts with a hand of 7 Occupation cards (of more than 160 total) and 7 Minor Improvement cards (of more than 140 total) that he may use during the game if they fi t in his/her strategy. This amounts to countless strategies, some depending on your card hand. Sometimes it’s a good choice to stay on course, sometimes you better react on what your opponents do.\n    Agricola can also be played without cards (family game) and can even be played solo."},
  {title: "Thurn and Taxis", image_url: "http://upload.wikimedia.org/wikipedia/en/0/03/Thurn_and_Taxis.jpg", designer: "Karen Seyfarth and Andreas Seyfarth", description: "In 1490, Kaiser Maximilian I awarded Franz von Taxis the contract to deliver mail between the Kaiser’s residences in Innsbruck and Brussels.He did such a good job, that postal services in the country continue to be connected with the name Thurn and Taxis. With the introduction of postal carriages in the middle of the 17th century, members of the family were raised to Count status and given the hereditary title of Postmaster General. The game begins at this point in history.Can you emulate the achievements of this family and build a successful postal network? Do you have the talent to connect the right cities to create an effective network and not lose sight of the need to acquire new carriages when they are needed? Plan your moves carefully and watch your opponents’ moves carefully, so you are prepared to respond to them.The game takes you back in time and gives you challenges that will bring you back to the game over and over."},
  {title: "Acquire", image_url: "http://a3.res.cloudinary.com/csicdn/image/upload/c_pad,h_300,w_300/v1/Images/Products/Misc%20Art/Avalon%20Hill/full/ah_acquire.jpg", designer: "Sid Sackson", description: "As a powerful real estate tycoon, there are only seven hotel chains in the world worthy of your attention. Using nothing but your wealth and wits, you must vie against other business magnates to manipulate construction and capitalize on mergers -- buying, trading, and selling stocks in order to get the greatest return on your investments.\n     \n     Acquire challenges you to pit your resources snf resolve against other players in this high-finance game of speculation and strategy!"},
  {title: "Betrayal at House on the Hill", image_url: "http://ecx.images-amazon.com/images/I/71DD%2B65rEQL._SL1200_.jpg", designer: "Bruce Glassco, Rob Daviau, Bill McQuillan, Mike Selinker, and Teeuwynn Woodruff", description: "Build a House of Terror. Tile by Tile.\n     \n     It's never the same game twice. As one of twelve mysterious characters, you'll explore a house filled with deadly secrets. As you play, you'll build the house. But beware! One of your fellow players will betray you. The traitor will test your sanity as you use all your skills to survive.\n     \n     With fifty fiendish scenarios, Betrayal at House on the Hill puts you face-to-face with legendary monsters, modern nightmares ... and your friends."},
  {title: "Citadels", image_url: "http://www.gamersquestsa.com/media/catalog/product/cache/1/image/1200x1200/9df78eab33525d08d6e5fb8d27136e95/c/i/citadels.jpg", designer: "Bruno Faidutti", description: "Feats of architecture rise alongside new prisons and slums. Nobles intrigue relentlessly, constructing fortresses and palaces, squeezing the districts of the city for the last ducats. In the shadows, the refuse of the underworld preys on the nobles, with tales of new murders and robberies appearing daily. They say the King will aid a new city in ousting the Merchant Guild, but if the city strongboxes are inexplicably emptied, they may need the Merchants more than they thought…\n    \n    Citadels is a game of city-building and intrigue for two to eight players. In Citadels, each player is striving to complete his own city, consisting of eight separate districts. As the players labor to build their cities, they are also forced to vie for the benefits granted by enlisting the support of certain formidable Characters. Timing and careful planning take vital importance in the uncertain business of city construction, and a successful prelate must be willing to bluff and able to switch his plans at a moment’s uneasy notice."},
  {title: "Love Letter", image_url: "https://cf.geekdo-images.com/images/pic1401448.jpg", designer: "Seiji Kanai", description: "In the wake of the queen’s arrest, all the eligible young men of Tempest (and many not so young) seek to woo Princess Annette. Unfortunately, she has locked herself in the palace, and everyone must rely on those within the palace to bring their romantic letters to her. Will yours reach her first?\n    \n    Love Letter is a game of risk, deduction, and luck, for 2–4 players. Get your love letter into Princess Annette’s hands while keeping other players’ letters away. Powerful cards lead to early gains, but make you a target. Rely on weaker cards for too long and your letter may be tossed in the fire!"},
  {title: "Dixit", image_url: "http://www.starlitcitadel.com/games/media/catalog/product/cache/7/image/66ffab2fe682907a17e1679a1175a522/d/i/dixit+front.jpg", designer: "Jean-Louis Roubira", description: "Every picture tells a story – but what story will your picture tell?\n    \n    Dixit is the lovingly illustrated game of creative guesswork, where your imagination unlocks the tale. In this award-winning board game, players will use the beautiful imagery on their cards to bluff their opponents and guess which image matches the story. Guessing right is only half the battle – to really succeed, you’ll have to get your friends to decide that your card tells the story!\n    Every turn, the storyteller will call out a short phrase or word to match the image on his card. Then each player will choose the card that most closely matches that phrase, and then everyone must guess which card the storyteller saw when he invented his brief tale. Correctly guess the storyteller’s card, and you’ll move ahead. Convince everyone else that your card is best, and you’ll do even better.\n    Dixit is a wonderfully simple game, playable by nearly anyone with whom you share a common language. With a fantastic range of beautiful illustrations and rules that can be understood by children and adults alike, Dixit will appeal to anyone with an imagination. It’s no surprise that Dixit won the Spiel de Jahres award for game design in 2010. It is brilliant and simple, beautiful and imaginative, and fun for all."},
  {title: "Magic: the Gathering", image_url: "http://upload.wikimedia.org/wikipedia/en/a/aa/Magic_the_gathering-card_back.jpg", designer: "Richard Garfield", description: "In Magic, you play the role of a planeswalker—a powerful wizard who fights other planeswalkers for glory, knowledge, and conquest. Your deck of cards represents all the weapons in your arsenal. It contains the spells you know and the creatures you can summon to fight for you.\n    \n    This is the oldest of the trading card game (TCG) genre. Cards are categorized as common, uncommon, rare, and mythic rare and sold in random packs containing a variety of cards. Players collect cards and build decks out of their collection.\n    \n    Players build a deck of cards and duel against an opponent's deck. The first player to reduce his opponent to 0 life (or meet another set win condition) wins the game.\n    \n    Deck building is major part of the game. There are over 17,000 different cards from which to build your deck!\n    \n    Players randomly draw spells to see what they get and can play each turn. Although this limits your choices, there is a lot of strategy in how you play those spells. A robust list of game mechanics, including intricate rules for reactive card play called 'the stack,' provide for rich tactics and tough choices each turn.\n      \n      Though traditionally a two-player duel, there are several casual and tournament formats to Magic that allow more players to play."},
  {title: "The Resistance", image_url: "http://img.ozgameshop.com/toys_and_games/board_games/the_resistance_2nd_edition_raw.jpg", designer: "Don Eskridge", description: "“The Empire must fall. Our mission must succeed. By destroying their key bases, we will shatter Imperial strength and liberate our people. Yet spies have infiltrated our ranks, ready for sabotage. We must unmask them. In five nights we reshape destiny or die trying. We are the Resistance!”\n    \n    The Resistance is a very intense social deduction game for 5-10 players. While it shares similiarities with games like Werewolf, Mafia and even Battlestar Galactica it has many very unique features such as a quick 30 minute play time, no moderator required and no player elimination.\n      \n      Set in the near future, The Resistance pits a small group of resistance fighters against a powerful and corrupt government. The resistance has launched a series of bold and daring missions to bring the governement to its knees. Unfortunately spies have infiltrated the resistance ranks, ready to sabotage the carefully crafted plans. Even a single spy can take down a resistance mission team, choose your teams carefully or forever lose your chance for freedom."},
  {title: "Galaxy Trucker", image_url: "http://riograndegames.com/uploads/Game/Preview-1_269.jpeg", designer: "Vlaada Chvátil", description: "Corporation Incorporated is an interplanetary construction firm that builds sewer systems and low-income housing on the less-developed planets of the Galaxy. For years, Corp Inc. has tottered on the brink of bankruptcy: transporting building materials to the edge of the Galaxy, where the need for their services is greatest, is a risky business.\n    The company was saved by a few visionaries on the board of directors. Instead\n    of shipping materials to the Periphery, they reasoned, why not build the materials into spacecraft and let them ship themselves? Furthermore, why hire pilots if there are nut-cases who will do it for free?\n    That’s where you come in. Just sign the contract, and you gain unrestricted access to a Corp Inc. Warehouse. Build your own space ship from the available prefabricated components, and fly it to the Periphery. Of course, you may have to eat a loss, but any profits you make along the way are yours to keep, and Corporation Incorporated will pay you a bonus for quick delivery.\n      It’s possible that you will end up with an insurmountable debt and finish your days panhandling on the streets of Deneb III, but if Lady Luck should smile upon you, you just might find yourself among the 10 billion richest people in the Galaxy!"},
  {title: "Memoir '44", image_url: "http://upload.wikimedia.org/wikipedia/en/thumb/2/24/Memoir44_USBox.jpg/250px-Memoir44_USBox.jpg", designer: "Richard Borg", description: "Memoir '44 is a unique historical game where players command a horde of little plastic Army men facing-off in dozens of WWII battles on an oversize hex game board.\n    \n    Each battle scenario mimics the historical terrain, troop placements and objectives of each army. Deploying forces through a variety of Command cards, the smart commander uses the unique skills of his units - infantry, paratroopers, tanks, artillery, commandos and resistance fighters - to its greatest strength.\n    \n    Easy to learn and fast-paced, Memoir '44 requires strategic card play, timely dice rolling and an aggressive, yet flexible battle plan to achieve victory!"}
])
Rating.create!([
  {user_id: 1, game_id: 5, score: 45},
  {user_id: 1, game_id: 23, score: 23},
  {user_id: 1, game_id: 38, score: 4},
  {user_id: 1, game_id: 44, score: 49},
  {user_id: 1, game_id: 26, score: 46},
  {user_id: 1, game_id: 36, score: 47},
  {user_id: 3, game_id: 51, score: 32},
  {user_id: 3, game_id: 50, score: 35},
  {user_id: 3, game_id: 48, score: 44},
  {user_id: 3, game_id: 47, score: 13},
  {user_id: 3, game_id: 46, score: 47},
  {user_id: 3, game_id: 45, score: 17},
  {user_id: 3, game_id: 44, score: 25},
  {user_id: 3, game_id: 43, score: 13},
  {user_id: 3, game_id: 41, score: 43},
  {user_id: 3, game_id: 39, score: 34},
  {user_id: 3, game_id: 38, score: 36},
  {user_id: 3, game_id: 37, score: 25},
  {user_id: 3, game_id: 36, score: 34},
  {user_id: 3, game_id: 35, score: 34},
  {user_id: 3, game_id: 34, score: 31},
  {user_id: 3, game_id: 33, score: 40},
  {user_id: 3, game_id: 32, score: 23},
  {user_id: 3, game_id: 31, score: 18},
  {user_id: 3, game_id: 30, score: 37},
  {user_id: 3, game_id: 29, score: 23},
  {user_id: 3, game_id: 28, score: 33},
  {user_id: 3, game_id: 49, score: 36},
  {user_id: 3, game_id: 27, score: 15},
  {user_id: 3, game_id: 26, score: 28},
  {user_id: 3, game_id: 25, score: 18},
  {user_id: 3, game_id: 24, score: 25},
  {user_id: 3, game_id: 23, score: 39},
  {user_id: 3, game_id: 22, score: 36},
  {user_id: 3, game_id: 21, score: 38},
  {user_id: 3, game_id: 20, score: 27},
  {user_id: 3, game_id: 19, score: 38},
  {user_id: 3, game_id: 18, score: 43},
  {user_id: 3, game_id: 17, score: 34},
  {user_id: 3, game_id: 40, score: 2},
  {user_id: 3, game_id: 42, score: 11},
  {user_id: 4, game_id: 1, score: 18},
  {user_id: 4, game_id: 49, score: 12},
  {user_id: 4, game_id: 51, score: 3},
  {user_id: 5, game_id: 1, score: 43},
  {user_id: 5, game_id: 49, score: 16},
  {user_id: 5, game_id: 51, score: 6},
  {user_id: 6, game_id: 1, score: 22},
  {user_id: 3, game_id: 1, score: 48},
  {user_id: 3, game_id: 2, score: 7},
  {user_id: 3, game_id: 3, score: 50},
  {user_id: 3, game_id: 4, score: 15},
  {user_id: 3, game_id: 5, score: 32},
  {user_id: 3, game_id: 6, score: 38},
  {user_id: 3, game_id: 7, score: 34},
  {user_id: 3, game_id: 8, score: 42},
  {user_id: 3, game_id: 9, score: 22},
  {user_id: 3, game_id: 10, score: 28},
  {user_id: 3, game_id: 11, score: 47},
  {user_id: 3, game_id: 12, score: 46},
  {user_id: 3, game_id: 13, score: 48},
  {user_id: 3, game_id: 14, score: 13},
  {user_id: 4, game_id: 2, score: 12},
  {user_id: 4, game_id: 3, score: 19},
  {user_id: 4, game_id: 4, score: 38},
  {user_id: 4, game_id: 5, score: 25},
  {user_id: 4, game_id: 6, score: 30},
  {user_id: 4, game_id: 7, score: 28},
  {user_id: 4, game_id: 8, score: 47},
  {user_id: 4, game_id: 9, score: 33},
  {user_id: 4, game_id: 10, score: 49},
  {user_id: 4, game_id: 11, score: 22},
  {user_id: 4, game_id: 12, score: 49},
  {user_id: 4, game_id: 13, score: 4},
  {user_id: 4, game_id: 14, score: 36},
  {user_id: 4, game_id: 15, score: 14},
  {user_id: 4, game_id: 16, score: 40},
  {user_id: 4, game_id: 17, score: 12},
  {user_id: 4, game_id: 18, score: 3},
  {user_id: 4, game_id: 19, score: 21},
  {user_id: 4, game_id: 20, score: 27},
  {user_id: 4, game_id: 21, score: 33},
  {user_id: 4, game_id: 22, score: 12},
  {user_id: 4, game_id: 23, score: 39},
  {user_id: 4, game_id: 24, score: 48},
  {user_id: 4, game_id: 25, score: 48},
  {user_id: 4, game_id: 26, score: 35},
  {user_id: 4, game_id: 27, score: 15},
  {user_id: 4, game_id: 28, score: 21},
  {user_id: 4, game_id: 29, score: 35},
  {user_id: 4, game_id: 30, score: 33},
  {user_id: 4, game_id: 31, score: 14},
  {user_id: 4, game_id: 32, score: 20},
  {user_id: 4, game_id: 33, score: 10},
  {user_id: 4, game_id: 34, score: 1},
  {user_id: 4, game_id: 35, score: 31},
  {user_id: 4, game_id: 36, score: 35},
  {user_id: 4, game_id: 37, score: 36},
  {user_id: 4, game_id: 38, score: 24},
  {user_id: 4, game_id: 39, score: 16},
  {user_id: 4, game_id: 40, score: 9},
  {user_id: 4, game_id: 41, score: 50},
  {user_id: 4, game_id: 42, score: 19},
  {user_id: 4, game_id: 43, score: 31},
  {user_id: 4, game_id: 44, score: 28},
  {user_id: 4, game_id: 45, score: 23},
  {user_id: 4, game_id: 46, score: 43},
  {user_id: 4, game_id: 48, score: 47},
  {user_id: 4, game_id: 50, score: 14},
  {user_id: 5, game_id: 2, score: 35},
  {user_id: 5, game_id: 3, score: 32},
  {user_id: 5, game_id: 4, score: 24},
  {user_id: 5, game_id: 5, score: 33},
  {user_id: 5, game_id: 6, score: 22},
  {user_id: 5, game_id: 7, score: 20},
  {user_id: 5, game_id: 8, score: 20},
  {user_id: 5, game_id: 9, score: 12},
  {user_id: 5, game_id: 10, score: 48},
  {user_id: 5, game_id: 11, score: 45},
  {user_id: 5, game_id: 12, score: 34},
  {user_id: 5, game_id: 13, score: 20},
  {user_id: 5, game_id: 14, score: 49},
  {user_id: 5, game_id: 15, score: 4},
  {user_id: 5, game_id: 16, score: 40},
  {user_id: 5, game_id: 17, score: 28},
  {user_id: 5, game_id: 18, score: 11},
  {user_id: 5, game_id: 19, score: 31},
  {user_id: 5, game_id: 20, score: 29},
  {user_id: 5, game_id: 21, score: 33},
  {user_id: 5, game_id: 22, score: 39},
  {user_id: 5, game_id: 23, score: 49},
  {user_id: 5, game_id: 24, score: 41},
  {user_id: 5, game_id: 25, score: 26},
  {user_id: 5, game_id: 26, score: 13},
  {user_id: 5, game_id: 27, score: 34},
  {user_id: 5, game_id: 28, score: 8},
  {user_id: 5, game_id: 29, score: 43},
  {user_id: 5, game_id: 30, score: 41},
  {user_id: 5, game_id: 31, score: 13},
  {user_id: 5, game_id: 32, score: 49},
  {user_id: 5, game_id: 33, score: 29},
  {user_id: 5, game_id: 34, score: 27},
  {user_id: 5, game_id: 35, score: 35},
  {user_id: 5, game_id: 36, score: 48},
  {user_id: 5, game_id: 37, score: 50},
  {user_id: 5, game_id: 38, score: 41},
  {user_id: 5, game_id: 39, score: 35},
  {user_id: 5, game_id: 40, score: 38},
  {user_id: 5, game_id: 41, score: 5},
  {user_id: 5, game_id: 42, score: 14},
  {user_id: 5, game_id: 43, score: 2},
  {user_id: 5, game_id: 44, score: 25},
  {user_id: 5, game_id: 45, score: 48},
  {user_id: 5, game_id: 46, score: 28},
  {user_id: 5, game_id: 48, score: 47},
  {user_id: 5, game_id: 50, score: 42},
  {user_id: 6, game_id: 2, score: 3},
  {user_id: 6, game_id: 49, score: 20},
  {user_id: 6, game_id: 51, score: 50},
  {user_id: 7, game_id: 1, score: 15},
  {user_id: 7, game_id: 49, score: 37},
  {user_id: 7, game_id: 51, score: 3},
  {user_id: 8, game_id: 1, score: 35},
  {user_id: 8, game_id: 49, score: 32},
  {user_id: 6, game_id: 3, score: 37},
  {user_id: 6, game_id: 4, score: 5},
  {user_id: 6, game_id: 5, score: 46},
  {user_id: 6, game_id: 6, score: 11},
  {user_id: 6, game_id: 7, score: 15},
  {user_id: 6, game_id: 8, score: 32},
  {user_id: 6, game_id: 9, score: 15},
  {user_id: 6, game_id: 10, score: 36},
  {user_id: 6, game_id: 11, score: 21},
  {user_id: 6, game_id: 12, score: 25},
  {user_id: 6, game_id: 13, score: 30},
  {user_id: 6, game_id: 14, score: 14},
  {user_id: 6, game_id: 15, score: 12},
  {user_id: 6, game_id: 16, score: 45},
  {user_id: 6, game_id: 17, score: 21},
  {user_id: 6, game_id: 18, score: 34},
  {user_id: 6, game_id: 19, score: 39},
  {user_id: 6, game_id: 20, score: 40},
  {user_id: 6, game_id: 21, score: 38},
  {user_id: 6, game_id: 22, score: 37},
  {user_id: 6, game_id: 23, score: 1},
  {user_id: 6, game_id: 24, score: 41},
  {user_id: 6, game_id: 25, score: 27},
  {user_id: 6, game_id: 26, score: 4},
  {user_id: 6, game_id: 27, score: 22},
  {user_id: 6, game_id: 28, score: 19},
  {user_id: 6, game_id: 29, score: 28},
  {user_id: 6, game_id: 30, score: 27},
  {user_id: 6, game_id: 31, score: 32},
  {user_id: 6, game_id: 32, score: 43},
  {user_id: 6, game_id: 33, score: 23},
  {user_id: 6, game_id: 34, score: 1},
  {user_id: 6, game_id: 35, score: 19},
  {user_id: 6, game_id: 36, score: 29},
  {user_id: 6, game_id: 37, score: 21},
  {user_id: 6, game_id: 38, score: 21},
  {user_id: 6, game_id: 39, score: 7},
  {user_id: 6, game_id: 40, score: 9},
  {user_id: 6, game_id: 41, score: 48},
  {user_id: 6, game_id: 42, score: 36},
  {user_id: 6, game_id: 43, score: 29},
  {user_id: 6, game_id: 44, score: 25},
  {user_id: 6, game_id: 45, score: 23},
  {user_id: 6, game_id: 46, score: 46},
  {user_id: 6, game_id: 50, score: 17},
  {user_id: 7, game_id: 2, score: 46},
  {user_id: 7, game_id: 3, score: 39},
  {user_id: 7, game_id: 4, score: 18},
  {user_id: 7, game_id: 5, score: 10},
  {user_id: 7, game_id: 6, score: 39},
  {user_id: 7, game_id: 7, score: 8},
  {user_id: 7, game_id: 8, score: 12},
  {user_id: 7, game_id: 9, score: 23},
  {user_id: 7, game_id: 10, score: 41},
  {user_id: 7, game_id: 11, score: 33},
  {user_id: 7, game_id: 12, score: 7},
  {user_id: 7, game_id: 13, score: 23},
  {user_id: 7, game_id: 14, score: 25},
  {user_id: 7, game_id: 16, score: 41},
  {user_id: 7, game_id: 17, score: 9},
  {user_id: 7, game_id: 18, score: 47},
  {user_id: 7, game_id: 19, score: 36},
  {user_id: 7, game_id: 20, score: 47},
  {user_id: 7, game_id: 21, score: 36},
  {user_id: 7, game_id: 22, score: 27},
  {user_id: 7, game_id: 23, score: 29},
  {user_id: 7, game_id: 24, score: 15},
  {user_id: 7, game_id: 25, score: 38},
  {user_id: 7, game_id: 26, score: 4},
  {user_id: 7, game_id: 27, score: 19},
  {user_id: 7, game_id: 28, score: 34},
  {user_id: 7, game_id: 29, score: 4},
  {user_id: 7, game_id: 31, score: 44},
  {user_id: 7, game_id: 32, score: 41},
  {user_id: 7, game_id: 33, score: 43},
  {user_id: 7, game_id: 34, score: 33},
  {user_id: 7, game_id: 35, score: 2},
  {user_id: 7, game_id: 36, score: 49},
  {user_id: 7, game_id: 37, score: 50},
  {user_id: 7, game_id: 38, score: 12},
  {user_id: 7, game_id: 39, score: 27},
  {user_id: 7, game_id: 40, score: 36},
  {user_id: 7, game_id: 41, score: 40},
  {user_id: 7, game_id: 42, score: 32},
  {user_id: 7, game_id: 43, score: 27},
  {user_id: 7, game_id: 44, score: 29},
  {user_id: 7, game_id: 46, score: 32},
  {user_id: 7, game_id: 48, score: 30},
  {user_id: 7, game_id: 50, score: 9},
  {user_id: 8, game_id: 2, score: 39},
  {user_id: 8, game_id: 3, score: 35},
  {user_id: 8, game_id: 4, score: 13},
  {user_id: 8, game_id: 5, score: 16},
  {user_id: 8, game_id: 6, score: 9},
  {user_id: 8, game_id: 7, score: 19},
  {user_id: 8, game_id: 8, score: 8},
  {user_id: 8, game_id: 9, score: 29},
  {user_id: 8, game_id: 10, score: 7},
  {user_id: 8, game_id: 11, score: 3},
  {user_id: 8, game_id: 12, score: 4},
  {user_id: 8, game_id: 14, score: 32},
  {user_id: 8, game_id: 15, score: 13},
  {user_id: 8, game_id: 16, score: 50},
  {user_id: 8, game_id: 17, score: 7},
  {user_id: 8, game_id: 18, score: 49},
  {user_id: 8, game_id: 19, score: 5},
  {user_id: 8, game_id: 20, score: 35},
  {user_id: 8, game_id: 21, score: 15},
  {user_id: 8, game_id: 22, score: 43},
  {user_id: 8, game_id: 23, score: 49},
  {user_id: 8, game_id: 24, score: 18},
  {user_id: 8, game_id: 25, score: 32},
  {user_id: 8, game_id: 26, score: 22},
  {user_id: 8, game_id: 27, score: 10},
  {user_id: 8, game_id: 29, score: 8},
  {user_id: 8, game_id: 30, score: 18},
  {user_id: 8, game_id: 31, score: 26},
  {user_id: 8, game_id: 51, score: 23},
  {user_id: 9, game_id: 1, score: 20},
  {user_id: 9, game_id: 49, score: 32},
  {user_id: 9, game_id: 51, score: 44},
  {user_id: 10, game_id: 1, score: 35},
  {user_id: 10, game_id: 49, score: 11},
  {user_id: 10, game_id: 51, score: 50},
  {user_id: 11, game_id: 1, score: 20},
  {user_id: 8, game_id: 32, score: 1},
  {user_id: 8, game_id: 33, score: 15},
  {user_id: 8, game_id: 34, score: 24},
  {user_id: 8, game_id: 35, score: 34},
  {user_id: 8, game_id: 36, score: 48},
  {user_id: 8, game_id: 37, score: 23},
  {user_id: 8, game_id: 38, score: 22},
  {user_id: 8, game_id: 39, score: 42},
  {user_id: 8, game_id: 40, score: 1},
  {user_id: 8, game_id: 41, score: 4},
  {user_id: 8, game_id: 42, score: 6},
  {user_id: 8, game_id: 43, score: 3},
  {user_id: 8, game_id: 44, score: 6},
  {user_id: 8, game_id: 45, score: 20},
  {user_id: 8, game_id: 46, score: 41},
  {user_id: 8, game_id: 48, score: 35},
  {user_id: 8, game_id: 50, score: 45},
  {user_id: 9, game_id: 2, score: 22},
  {user_id: 9, game_id: 3, score: 38},
  {user_id: 9, game_id: 4, score: 10},
  {user_id: 9, game_id: 5, score: 6},
  {user_id: 9, game_id: 6, score: 7},
  {user_id: 9, game_id: 7, score: 8},
  {user_id: 9, game_id: 8, score: 8},
  {user_id: 9, game_id: 9, score: 49},
  {user_id: 9, game_id: 10, score: 20},
  {user_id: 9, game_id: 11, score: 37},
  {user_id: 9, game_id: 12, score: 7},
  {user_id: 9, game_id: 13, score: 30},
  {user_id: 9, game_id: 14, score: 6},
  {user_id: 9, game_id: 15, score: 48},
  {user_id: 9, game_id: 16, score: 50},
  {user_id: 9, game_id: 17, score: 19},
  {user_id: 9, game_id: 18, score: 30},
  {user_id: 9, game_id: 19, score: 33},
  {user_id: 9, game_id: 20, score: 45},
  {user_id: 9, game_id: 21, score: 48},
  {user_id: 9, game_id: 22, score: 37},
  {user_id: 9, game_id: 23, score: 13},
  {user_id: 9, game_id: 24, score: 22},
  {user_id: 9, game_id: 25, score: 14},
  {user_id: 9, game_id: 26, score: 40},
  {user_id: 9, game_id: 27, score: 40},
  {user_id: 9, game_id: 28, score: 25},
  {user_id: 9, game_id: 29, score: 47},
  {user_id: 9, game_id: 30, score: 1},
  {user_id: 9, game_id: 31, score: 26},
  {user_id: 9, game_id: 32, score: 41},
  {user_id: 9, game_id: 33, score: 37},
  {user_id: 9, game_id: 34, score: 5},
  {user_id: 9, game_id: 35, score: 24},
  {user_id: 9, game_id: 36, score: 9},
  {user_id: 9, game_id: 37, score: 29},
  {user_id: 9, game_id: 38, score: 23},
  {user_id: 9, game_id: 39, score: 49},
  {user_id: 9, game_id: 40, score: 40},
  {user_id: 9, game_id: 41, score: 2},
  {user_id: 9, game_id: 42, score: 28},
  {user_id: 9, game_id: 43, score: 2},
  {user_id: 9, game_id: 44, score: 36},
  {user_id: 9, game_id: 45, score: 30},
  {user_id: 9, game_id: 46, score: 5},
  {user_id: 9, game_id: 48, score: 18},
  {user_id: 9, game_id: 50, score: 13},
  {user_id: 10, game_id: 2, score: 22},
  {user_id: 10, game_id: 3, score: 1},
  {user_id: 10, game_id: 4, score: 37},
  {user_id: 10, game_id: 5, score: 27},
  {user_id: 10, game_id: 6, score: 50},
  {user_id: 10, game_id: 7, score: 9},
  {user_id: 10, game_id: 8, score: 18},
  {user_id: 10, game_id: 9, score: 15},
  {user_id: 10, game_id: 11, score: 33},
  {user_id: 10, game_id: 12, score: 3},
  {user_id: 10, game_id: 13, score: 33},
  {user_id: 10, game_id: 14, score: 8},
  {user_id: 10, game_id: 15, score: 6},
  {user_id: 10, game_id: 16, score: 38},
  {user_id: 10, game_id: 17, score: 8},
  {user_id: 10, game_id: 18, score: 38},
  {user_id: 10, game_id: 19, score: 1},
  {user_id: 10, game_id: 20, score: 15},
  {user_id: 10, game_id: 21, score: 24},
  {user_id: 10, game_id: 22, score: 37},
  {user_id: 10, game_id: 23, score: 38},
  {user_id: 10, game_id: 24, score: 39},
  {user_id: 10, game_id: 26, score: 37},
  {user_id: 10, game_id: 27, score: 5},
  {user_id: 10, game_id: 28, score: 38},
  {user_id: 10, game_id: 29, score: 9},
  {user_id: 10, game_id: 30, score: 37},
  {user_id: 10, game_id: 31, score: 22},
  {user_id: 10, game_id: 32, score: 26},
  {user_id: 10, game_id: 33, score: 36},
  {user_id: 10, game_id: 34, score: 47},
  {user_id: 10, game_id: 35, score: 29},
  {user_id: 10, game_id: 36, score: 32},
  {user_id: 10, game_id: 37, score: 7},
  {user_id: 10, game_id: 38, score: 19},
  {user_id: 10, game_id: 39, score: 3},
  {user_id: 10, game_id: 41, score: 44},
  {user_id: 10, game_id: 42, score: 37},
  {user_id: 10, game_id: 43, score: 20},
  {user_id: 10, game_id: 44, score: 9},
  {user_id: 10, game_id: 45, score: 6},
  {user_id: 10, game_id: 46, score: 15},
  {user_id: 10, game_id: 48, score: 30},
  {user_id: 10, game_id: 50, score: 10},
  {user_id: 11, game_id: 2, score: 9},
  {user_id: 11, game_id: 3, score: 25},
  {user_id: 11, game_id: 4, score: 29},
  {user_id: 11, game_id: 5, score: 14},
  {user_id: 11, game_id: 6, score: 50},
  {user_id: 11, game_id: 7, score: 43},
  {user_id: 11, game_id: 9, score: 16},
  {user_id: 11, game_id: 49, score: 40},
  {user_id: 11, game_id: 51, score: 42},
  {user_id: 12, game_id: 1, score: 43},
  {user_id: 12, game_id: 49, score: 8},
  {user_id: 12, game_id: 51, score: 26},
  {user_id: 13, game_id: 1, score: 50},
  {user_id: 13, game_id: 49, score: 5},
  {user_id: 11, game_id: 10, score: 26},
  {user_id: 11, game_id: 11, score: 44},
  {user_id: 11, game_id: 12, score: 5},
  {user_id: 11, game_id: 13, score: 9},
  {user_id: 11, game_id: 14, score: 34},
  {user_id: 11, game_id: 15, score: 10},
  {user_id: 11, game_id: 16, score: 8},
  {user_id: 11, game_id: 17, score: 32},
  {user_id: 11, game_id: 18, score: 46},
  {user_id: 11, game_id: 19, score: 12},
  {user_id: 11, game_id: 20, score: 37},
  {user_id: 11, game_id: 21, score: 39},
  {user_id: 11, game_id: 22, score: 46},
  {user_id: 11, game_id: 23, score: 24},
  {user_id: 11, game_id: 24, score: 41},
  {user_id: 11, game_id: 25, score: 38},
  {user_id: 11, game_id: 26, score: 38},
  {user_id: 11, game_id: 27, score: 41},
  {user_id: 11, game_id: 28, score: 24},
  {user_id: 11, game_id: 29, score: 33},
  {user_id: 11, game_id: 30, score: 29},
  {user_id: 11, game_id: 31, score: 35},
  {user_id: 11, game_id: 32, score: 14},
  {user_id: 11, game_id: 33, score: 35},
  {user_id: 11, game_id: 34, score: 27},
  {user_id: 11, game_id: 35, score: 41},
  {user_id: 11, game_id: 36, score: 43},
  {user_id: 11, game_id: 37, score: 45},
  {user_id: 11, game_id: 38, score: 19},
  {user_id: 11, game_id: 39, score: 3},
  {user_id: 11, game_id: 40, score: 27},
  {user_id: 11, game_id: 41, score: 44},
  {user_id: 11, game_id: 42, score: 26},
  {user_id: 11, game_id: 43, score: 19},
  {user_id: 11, game_id: 44, score: 21},
  {user_id: 11, game_id: 45, score: 19},
  {user_id: 11, game_id: 46, score: 19},
  {user_id: 11, game_id: 48, score: 46},
  {user_id: 11, game_id: 50, score: 31},
  {user_id: 12, game_id: 2, score: 40},
  {user_id: 12, game_id: 3, score: 38},
  {user_id: 12, game_id: 4, score: 24},
  {user_id: 12, game_id: 5, score: 45},
  {user_id: 12, game_id: 6, score: 22},
  {user_id: 12, game_id: 8, score: 17},
  {user_id: 12, game_id: 9, score: 13},
  {user_id: 12, game_id: 10, score: 40},
  {user_id: 12, game_id: 11, score: 18},
  {user_id: 12, game_id: 12, score: 42},
  {user_id: 12, game_id: 13, score: 26},
  {user_id: 12, game_id: 14, score: 21},
  {user_id: 12, game_id: 15, score: 42},
  {user_id: 12, game_id: 16, score: 20},
  {user_id: 12, game_id: 17, score: 25},
  {user_id: 12, game_id: 18, score: 27},
  {user_id: 12, game_id: 19, score: 15},
  {user_id: 12, game_id: 20, score: 34},
  {user_id: 12, game_id: 21, score: 47},
  {user_id: 12, game_id: 23, score: 8},
  {user_id: 12, game_id: 24, score: 6},
  {user_id: 12, game_id: 25, score: 12},
  {user_id: 12, game_id: 26, score: 33},
  {user_id: 12, game_id: 27, score: 31},
  {user_id: 12, game_id: 28, score: 29},
  {user_id: 12, game_id: 29, score: 15},
  {user_id: 12, game_id: 30, score: 16},
  {user_id: 12, game_id: 31, score: 23},
  {user_id: 12, game_id: 32, score: 33},
  {user_id: 12, game_id: 33, score: 11},
  {user_id: 12, game_id: 34, score: 18},
  {user_id: 12, game_id: 35, score: 19},
  {user_id: 12, game_id: 36, score: 33},
  {user_id: 12, game_id: 38, score: 20},
  {user_id: 12, game_id: 39, score: 8},
  {user_id: 12, game_id: 40, score: 2},
  {user_id: 12, game_id: 41, score: 16},
  {user_id: 12, game_id: 42, score: 14},
  {user_id: 12, game_id: 43, score: 45},
  {user_id: 12, game_id: 44, score: 48},
  {user_id: 12, game_id: 45, score: 28},
  {user_id: 12, game_id: 46, score: 18},
  {user_id: 12, game_id: 48, score: 16},
  {user_id: 12, game_id: 50, score: 19},
  {user_id: 13, game_id: 2, score: 37},
  {user_id: 13, game_id: 3, score: 6},
  {user_id: 13, game_id: 4, score: 5},
  {user_id: 13, game_id: 6, score: 39},
  {user_id: 13, game_id: 7, score: 40},
  {user_id: 13, game_id: 8, score: 1},
  {user_id: 13, game_id: 9, score: 48},
  {user_id: 13, game_id: 10, score: 44},
  {user_id: 13, game_id: 11, score: 39},
  {user_id: 13, game_id: 12, score: 9},
  {user_id: 13, game_id: 13, score: 17},
  {user_id: 13, game_id: 14, score: 27},
  {user_id: 13, game_id: 15, score: 30},
  {user_id: 13, game_id: 16, score: 42},
  {user_id: 13, game_id: 17, score: 28},
  {user_id: 13, game_id: 18, score: 5},
  {user_id: 13, game_id: 19, score: 46},
  {user_id: 13, game_id: 21, score: 20},
  {user_id: 13, game_id: 22, score: 38},
  {user_id: 13, game_id: 23, score: 50},
  {user_id: 13, game_id: 24, score: 13},
  {user_id: 13, game_id: 25, score: 41},
  {user_id: 13, game_id: 26, score: 40},
  {user_id: 13, game_id: 27, score: 11},
  {user_id: 13, game_id: 28, score: 21},
  {user_id: 13, game_id: 29, score: 6},
  {user_id: 13, game_id: 30, score: 26},
  {user_id: 13, game_id: 31, score: 5},
  {user_id: 13, game_id: 32, score: 32},
  {user_id: 13, game_id: 33, score: 10},
  {user_id: 13, game_id: 34, score: 21},
  {user_id: 13, game_id: 36, score: 18},
  {user_id: 13, game_id: 37, score: 4},
  {user_id: 13, game_id: 38, score: 35},
  {user_id: 13, game_id: 51, score: 35},
  {user_id: 14, game_id: 1, score: 41},
  {user_id: 14, game_id: 49, score: 35},
  {user_id: 14, game_id: 51, score: 32},
  {user_id: 15, game_id: 1, score: 50},
  {user_id: 15, game_id: 49, score: 13},
  {user_id: 15, game_id: 51, score: 5},
  {user_id: 16, game_id: 1, score: 22},
  {user_id: 13, game_id: 39, score: 33},
  {user_id: 13, game_id: 40, score: 6},
  {user_id: 13, game_id: 41, score: 29},
  {user_id: 13, game_id: 42, score: 20},
  {user_id: 13, game_id: 43, score: 2},
  {user_id: 13, game_id: 44, score: 41},
  {user_id: 13, game_id: 45, score: 9},
  {user_id: 13, game_id: 46, score: 6},
  {user_id: 13, game_id: 48, score: 23},
  {user_id: 13, game_id: 50, score: 41},
  {user_id: 14, game_id: 2, score: 41},
  {user_id: 14, game_id: 3, score: 3},
  {user_id: 14, game_id: 4, score: 44},
  {user_id: 14, game_id: 5, score: 35},
  {user_id: 14, game_id: 6, score: 17},
  {user_id: 14, game_id: 7, score: 9},
  {user_id: 14, game_id: 8, score: 47},
  {user_id: 14, game_id: 9, score: 42},
  {user_id: 14, game_id: 10, score: 2},
  {user_id: 14, game_id: 11, score: 27},
  {user_id: 14, game_id: 12, score: 37},
  {user_id: 14, game_id: 13, score: 24},
  {user_id: 14, game_id: 14, score: 23},
  {user_id: 14, game_id: 15, score: 2},
  {user_id: 14, game_id: 16, score: 9},
  {user_id: 14, game_id: 17, score: 24},
  {user_id: 14, game_id: 18, score: 29},
  {user_id: 14, game_id: 19, score: 47},
  {user_id: 14, game_id: 20, score: 17},
  {user_id: 14, game_id: 21, score: 20},
  {user_id: 14, game_id: 22, score: 22},
  {user_id: 14, game_id: 23, score: 9},
  {user_id: 14, game_id: 24, score: 50},
  {user_id: 14, game_id: 25, score: 17},
  {user_id: 14, game_id: 26, score: 8},
  {user_id: 14, game_id: 27, score: 28},
  {user_id: 14, game_id: 28, score: 37},
  {user_id: 14, game_id: 29, score: 25},
  {user_id: 14, game_id: 30, score: 46},
  {user_id: 14, game_id: 31, score: 24},
  {user_id: 14, game_id: 32, score: 4},
  {user_id: 14, game_id: 33, score: 44},
  {user_id: 14, game_id: 34, score: 27},
  {user_id: 14, game_id: 35, score: 25},
  {user_id: 14, game_id: 36, score: 18},
  {user_id: 14, game_id: 37, score: 24},
  {user_id: 14, game_id: 38, score: 42},
  {user_id: 14, game_id: 39, score: 39},
  {user_id: 14, game_id: 40, score: 40},
  {user_id: 14, game_id: 41, score: 19},
  {user_id: 14, game_id: 42, score: 44},
  {user_id: 14, game_id: 43, score: 21},
  {user_id: 14, game_id: 44, score: 42},
  {user_id: 14, game_id: 45, score: 11},
  {user_id: 14, game_id: 46, score: 46},
  {user_id: 14, game_id: 48, score: 42},
  {user_id: 14, game_id: 50, score: 31},
  {user_id: 15, game_id: 2, score: 40},
  {user_id: 15, game_id: 3, score: 37},
  {user_id: 15, game_id: 4, score: 42},
  {user_id: 15, game_id: 5, score: 20},
  {user_id: 15, game_id: 6, score: 40},
  {user_id: 15, game_id: 7, score: 33},
  {user_id: 15, game_id: 8, score: 24},
  {user_id: 15, game_id: 9, score: 37},
  {user_id: 15, game_id: 10, score: 22},
  {user_id: 15, game_id: 11, score: 38},
  {user_id: 15, game_id: 12, score: 10},
  {user_id: 15, game_id: 13, score: 8},
  {user_id: 15, game_id: 14, score: 6},
  {user_id: 15, game_id: 15, score: 45},
  {user_id: 15, game_id: 16, score: 19},
  {user_id: 15, game_id: 18, score: 37},
  {user_id: 15, game_id: 19, score: 25},
  {user_id: 15, game_id: 20, score: 44},
  {user_id: 15, game_id: 21, score: 43},
  {user_id: 15, game_id: 22, score: 44},
  {user_id: 15, game_id: 23, score: 5},
  {user_id: 15, game_id: 24, score: 20},
  {user_id: 15, game_id: 25, score: 45},
  {user_id: 15, game_id: 26, score: 41},
  {user_id: 15, game_id: 27, score: 45},
  {user_id: 15, game_id: 28, score: 34},
  {user_id: 15, game_id: 29, score: 1},
  {user_id: 15, game_id: 30, score: 13},
  {user_id: 15, game_id: 31, score: 31},
  {user_id: 15, game_id: 33, score: 2},
  {user_id: 15, game_id: 34, score: 24},
  {user_id: 15, game_id: 35, score: 25},
  {user_id: 15, game_id: 36, score: 43},
  {user_id: 15, game_id: 37, score: 42},
  {user_id: 15, game_id: 38, score: 27},
  {user_id: 15, game_id: 39, score: 15},
  {user_id: 15, game_id: 40, score: 7},
  {user_id: 15, game_id: 41, score: 20},
  {user_id: 15, game_id: 42, score: 9},
  {user_id: 15, game_id: 43, score: 9},
  {user_id: 15, game_id: 44, score: 42},
  {user_id: 15, game_id: 45, score: 47},
  {user_id: 15, game_id: 46, score: 6},
  {user_id: 15, game_id: 50, score: 30},
  {user_id: 16, game_id: 2, score: 40},
  {user_id: 16, game_id: 3, score: 1},
  {user_id: 16, game_id: 4, score: 5},
  {user_id: 16, game_id: 5, score: 20},
  {user_id: 16, game_id: 6, score: 17},
  {user_id: 16, game_id: 7, score: 2},
  {user_id: 16, game_id: 8, score: 12},
  {user_id: 16, game_id: 9, score: 33},
  {user_id: 16, game_id: 10, score: 16},
  {user_id: 16, game_id: 11, score: 3},
  {user_id: 16, game_id: 12, score: 27},
  {user_id: 16, game_id: 13, score: 23},
  {user_id: 16, game_id: 14, score: 12},
  {user_id: 16, game_id: 16, score: 36},
  {user_id: 16, game_id: 49, score: 40},
  {user_id: 16, game_id: 51, score: 48},
  {user_id: 17, game_id: 1, score: 14},
  {user_id: 17, game_id: 49, score: 26},
  {user_id: 17, game_id: 51, score: 25},
  {user_id: 18, game_id: 1, score: 18},
  {user_id: 18, game_id: 49, score: 46},
  {user_id: 16, game_id: 17, score: 48},
  {user_id: 16, game_id: 18, score: 19},
  {user_id: 16, game_id: 19, score: 41},
  {user_id: 16, game_id: 20, score: 3},
  {user_id: 16, game_id: 21, score: 24},
  {user_id: 16, game_id: 22, score: 15},
  {user_id: 16, game_id: 23, score: 30},
  {user_id: 16, game_id: 24, score: 35},
  {user_id: 16, game_id: 25, score: 7},
  {user_id: 16, game_id: 26, score: 21},
  {user_id: 16, game_id: 27, score: 39},
  {user_id: 16, game_id: 28, score: 16},
  {user_id: 16, game_id: 29, score: 7},
  {user_id: 16, game_id: 30, score: 32},
  {user_id: 16, game_id: 31, score: 10},
  {user_id: 16, game_id: 32, score: 32},
  {user_id: 16, game_id: 33, score: 14},
  {user_id: 16, game_id: 34, score: 27},
  {user_id: 16, game_id: 35, score: 46},
  {user_id: 16, game_id: 36, score: 5},
  {user_id: 16, game_id: 37, score: 15},
  {user_id: 16, game_id: 38, score: 33},
  {user_id: 16, game_id: 39, score: 47},
  {user_id: 16, game_id: 40, score: 43},
  {user_id: 16, game_id: 41, score: 44},
  {user_id: 16, game_id: 42, score: 23},
  {user_id: 16, game_id: 43, score: 8},
  {user_id: 16, game_id: 44, score: 15},
  {user_id: 16, game_id: 45, score: 7},
  {user_id: 16, game_id: 46, score: 27},
  {user_id: 16, game_id: 48, score: 12},
  {user_id: 16, game_id: 50, score: 32},
  {user_id: 17, game_id: 2, score: 21},
  {user_id: 17, game_id: 3, score: 38},
  {user_id: 17, game_id: 4, score: 30},
  {user_id: 17, game_id: 5, score: 42},
  {user_id: 17, game_id: 6, score: 38},
  {user_id: 17, game_id: 7, score: 38},
  {user_id: 17, game_id: 8, score: 41},
  {user_id: 17, game_id: 9, score: 1},
  {user_id: 17, game_id: 10, score: 1},
  {user_id: 17, game_id: 11, score: 4},
  {user_id: 17, game_id: 12, score: 23},
  {user_id: 17, game_id: 13, score: 13},
  {user_id: 17, game_id: 15, score: 16},
  {user_id: 17, game_id: 16, score: 36},
  {user_id: 17, game_id: 17, score: 34},
  {user_id: 17, game_id: 18, score: 33},
  {user_id: 17, game_id: 19, score: 11},
  {user_id: 17, game_id: 20, score: 50},
  {user_id: 17, game_id: 21, score: 6},
  {user_id: 17, game_id: 22, score: 29},
  {user_id: 17, game_id: 23, score: 23},
  {user_id: 17, game_id: 24, score: 5},
  {user_id: 17, game_id: 25, score: 2},
  {user_id: 17, game_id: 26, score: 38},
  {user_id: 17, game_id: 27, score: 10},
  {user_id: 17, game_id: 28, score: 12},
  {user_id: 17, game_id: 30, score: 25},
  {user_id: 17, game_id: 31, score: 28},
  {user_id: 17, game_id: 32, score: 28},
  {user_id: 17, game_id: 33, score: 46},
  {user_id: 17, game_id: 34, score: 9},
  {user_id: 17, game_id: 35, score: 17},
  {user_id: 17, game_id: 36, score: 33},
  {user_id: 17, game_id: 37, score: 28},
  {user_id: 17, game_id: 38, score: 5},
  {user_id: 17, game_id: 39, score: 21},
  {user_id: 17, game_id: 40, score: 28},
  {user_id: 17, game_id: 41, score: 6},
  {user_id: 17, game_id: 42, score: 25},
  {user_id: 17, game_id: 43, score: 38},
  {user_id: 17, game_id: 45, score: 22},
  {user_id: 17, game_id: 46, score: 41},
  {user_id: 17, game_id: 48, score: 3},
  {user_id: 17, game_id: 50, score: 37},
  {user_id: 18, game_id: 2, score: 10},
  {user_id: 18, game_id: 3, score: 14},
  {user_id: 18, game_id: 4, score: 2},
  {user_id: 18, game_id: 5, score: 1},
  {user_id: 18, game_id: 6, score: 6},
  {user_id: 18, game_id: 7, score: 40},
  {user_id: 18, game_id: 8, score: 20},
  {user_id: 18, game_id: 9, score: 23},
  {user_id: 18, game_id: 10, score: 49},
  {user_id: 18, game_id: 11, score: 19},
  {user_id: 18, game_id: 13, score: 4},
  {user_id: 18, game_id: 14, score: 12},
  {user_id: 18, game_id: 15, score: 42},
  {user_id: 18, game_id: 16, score: 7},
  {user_id: 18, game_id: 17, score: 44},
  {user_id: 18, game_id: 18, score: 22},
  {user_id: 18, game_id: 19, score: 38},
  {user_id: 18, game_id: 20, score: 25},
  {user_id: 18, game_id: 21, score: 47},
  {user_id: 18, game_id: 22, score: 31},
  {user_id: 18, game_id: 23, score: 48},
  {user_id: 18, game_id: 24, score: 29},
  {user_id: 18, game_id: 25, score: 27},
  {user_id: 18, game_id: 26, score: 15},
  {user_id: 18, game_id: 28, score: 27},
  {user_id: 18, game_id: 29, score: 20},
  {user_id: 18, game_id: 30, score: 44},
  {user_id: 18, game_id: 31, score: 6},
  {user_id: 18, game_id: 32, score: 38},
  {user_id: 18, game_id: 33, score: 47},
  {user_id: 18, game_id: 34, score: 22},
  {user_id: 18, game_id: 35, score: 37},
  {user_id: 18, game_id: 36, score: 34},
  {user_id: 18, game_id: 37, score: 17},
  {user_id: 18, game_id: 38, score: 6},
  {user_id: 18, game_id: 39, score: 18},
  {user_id: 18, game_id: 40, score: 45},
  {user_id: 18, game_id: 41, score: 40},
  {user_id: 18, game_id: 43, score: 28},
  {user_id: 18, game_id: 44, score: 48},
  {user_id: 18, game_id: 45, score: 49},
  {user_id: 18, game_id: 51, score: 41},
  {user_id: 19, game_id: 1, score: 30},
  {user_id: 19, game_id: 49, score: 21},
  {user_id: 19, game_id: 51, score: 13},
  {user_id: 20, game_id: 1, score: 3},
  {user_id: 20, game_id: 49, score: 3},
  {user_id: 20, game_id: 51, score: 28},
  {user_id: 6, game_id: 48, score: 43},
  {user_id: 7, game_id: 15, score: 28},
  {user_id: 7, game_id: 30, score: 22},
  {user_id: 7, game_id: 45, score: 8},
  {user_id: 8, game_id: 13, score: 17},
  {user_id: 8, game_id: 28, score: 50},
  {user_id: 10, game_id: 10, score: 15},
  {user_id: 10, game_id: 25, score: 31},
  {user_id: 10, game_id: 40, score: 29},
  {user_id: 11, game_id: 8, score: 24},
  {user_id: 12, game_id: 7, score: 22},
  {user_id: 12, game_id: 22, score: 33},
  {user_id: 12, game_id: 37, score: 23},
  {user_id: 13, game_id: 5, score: 33},
  {user_id: 13, game_id: 20, score: 33},
  {user_id: 13, game_id: 35, score: 10},
  {user_id: 15, game_id: 17, score: 34},
  {user_id: 15, game_id: 32, score: 46},
  {user_id: 15, game_id: 48, score: 17},
  {user_id: 16, game_id: 15, score: 44},
  {user_id: 17, game_id: 14, score: 38},
  {user_id: 17, game_id: 29, score: 6},
  {user_id: 17, game_id: 44, score: 9},
  {user_id: 18, game_id: 12, score: 12},
  {user_id: 18, game_id: 27, score: 24},
  {user_id: 18, game_id: 46, score: 8},
  {user_id: 18, game_id: 48, score: 17},
  {user_id: 18, game_id: 50, score: 13},
  {user_id: 19, game_id: 2, score: 22},
  {user_id: 19, game_id: 3, score: 18},
  {user_id: 19, game_id: 4, score: 2},
  {user_id: 19, game_id: 5, score: 17},
  {user_id: 19, game_id: 6, score: 24},
  {user_id: 19, game_id: 7, score: 25},
  {user_id: 19, game_id: 8, score: 36},
  {user_id: 19, game_id: 9, score: 22},
  {user_id: 19, game_id: 10, score: 17},
  {user_id: 19, game_id: 11, score: 22},
  {user_id: 19, game_id: 12, score: 50},
  {user_id: 19, game_id: 13, score: 11},
  {user_id: 19, game_id: 14, score: 46},
  {user_id: 19, game_id: 15, score: 45},
  {user_id: 19, game_id: 16, score: 13},
  {user_id: 19, game_id: 17, score: 1},
  {user_id: 19, game_id: 18, score: 9},
  {user_id: 19, game_id: 19, score: 20},
  {user_id: 19, game_id: 20, score: 37},
  {user_id: 19, game_id: 21, score: 46},
  {user_id: 19, game_id: 22, score: 8},
  {user_id: 19, game_id: 23, score: 28},
  {user_id: 19, game_id: 24, score: 22},
  {user_id: 19, game_id: 25, score: 13},
  {user_id: 19, game_id: 26, score: 10},
  {user_id: 19, game_id: 27, score: 42},
  {user_id: 19, game_id: 28, score: 2},
  {user_id: 19, game_id: 29, score: 32},
  {user_id: 19, game_id: 30, score: 6},
  {user_id: 19, game_id: 31, score: 4},
  {user_id: 19, game_id: 32, score: 47},
  {user_id: 19, game_id: 33, score: 4},
  {user_id: 19, game_id: 34, score: 16},
  {user_id: 19, game_id: 35, score: 38},
  {user_id: 19, game_id: 36, score: 49},
  {user_id: 19, game_id: 37, score: 50},
  {user_id: 19, game_id: 38, score: 36},
  {user_id: 19, game_id: 39, score: 29},
  {user_id: 19, game_id: 40, score: 18},
  {user_id: 19, game_id: 41, score: 24},
  {user_id: 19, game_id: 42, score: 7},
  {user_id: 19, game_id: 44, score: 11},
  {user_id: 19, game_id: 45, score: 29},
  {user_id: 19, game_id: 46, score: 34},
  {user_id: 19, game_id: 48, score: 41},
  {user_id: 19, game_id: 50, score: 32},
  {user_id: 20, game_id: 2, score: 50},
  {user_id: 20, game_id: 3, score: 24},
  {user_id: 20, game_id: 4, score: 10},
  {user_id: 20, game_id: 5, score: 6},
  {user_id: 20, game_id: 6, score: 47},
  {user_id: 20, game_id: 7, score: 43},
  {user_id: 20, game_id: 8, score: 26},
  {user_id: 20, game_id: 9, score: 42},
  {user_id: 20, game_id: 10, score: 42},
  {user_id: 20, game_id: 12, score: 10},
  {user_id: 20, game_id: 13, score: 29},
  {user_id: 20, game_id: 14, score: 44},
  {user_id: 20, game_id: 15, score: 20},
  {user_id: 20, game_id: 16, score: 18},
  {user_id: 20, game_id: 17, score: 39},
  {user_id: 20, game_id: 18, score: 27},
  {user_id: 20, game_id: 19, score: 37},
  {user_id: 20, game_id: 20, score: 23},
  {user_id: 20, game_id: 21, score: 41},
  {user_id: 20, game_id: 22, score: 33},
  {user_id: 20, game_id: 23, score: 17},
  {user_id: 20, game_id: 24, score: 42},
  {user_id: 20, game_id: 25, score: 6},
  {user_id: 20, game_id: 27, score: 19},
  {user_id: 20, game_id: 28, score: 33},
  {user_id: 20, game_id: 29, score: 6},
  {user_id: 20, game_id: 30, score: 47},
  {user_id: 20, game_id: 31, score: 33},
  {user_id: 20, game_id: 32, score: 4},
  {user_id: 20, game_id: 33, score: 21},
  {user_id: 20, game_id: 34, score: 41},
  {user_id: 20, game_id: 35, score: 6},
  {user_id: 20, game_id: 36, score: 24},
  {user_id: 20, game_id: 37, score: 34},
  {user_id: 20, game_id: 38, score: 50},
  {user_id: 20, game_id: 39, score: 23},
  {user_id: 20, game_id: 40, score: 42},
  {user_id: 20, game_id: 42, score: 31},
  {user_id: 20, game_id: 43, score: 49},
  {user_id: 20, game_id: 44, score: 47},
  {user_id: 20, game_id: 45, score: 14},
  {user_id: 20, game_id: 46, score: 25},
  {user_id: 20, game_id: 48, score: 24},
  {user_id: 20, game_id: 50, score: 45},
  {user_id: 18, game_id: 42, score: 19},
  {user_id: 19, game_id: 43, score: 2},
  {user_id: 20, game_id: 11, score: 8},
  {user_id: 20, game_id: 26, score: 37},
  {user_id: 20, game_id: 41, score: 18}
])
Review.create!([
  {user_id: 1, game_id: 1, body: "Best game ever. Would play a million times. 6/5."},
  {user_id: 1, game_id: 4, body: "The theme is loose but really fun (everything is named after old Sci Fi authors; consider it a reading list), and the dice-based worker placement mechanic was wonderfully innovative the first time I saw it, and tons of fun. The game takes a little longer than it really needs to, and I don't recommend the expansions, but would absolutely recommend this as a second or third strategic game for a fairly new gamer."}
])
Shelf.create!([
  {title: "Geeky Games", user_id: 2},
  {title: "Design Games", user_id: 2},
  {title: "Cool Games", user_id: 1},
  {title: "Terrible Games", user_id: 2},
  {title: "Games To Remember", user_id: 1},
  {title: "Interesting Ideas", user_id: 1}
])
Shelving.create!([
  {shelf_id: 1, game_id: 3},
  {shelf_id: 1, game_id: 2},
  {shelf_id: 2, game_id: 1},
  {shelf_id: 3, game_id: 1},
  {shelf_id: 2, game_id: 2},
  {shelf_id: 4, game_id: 3},
  {shelf_id: 3, game_id: 4},
  {shelf_id: 5, game_id: 4},
  {shelf_id: 6, game_id: 4},
  {shelf_id: 5, game_id: 1}
])
